Home Page: Events/Networking Section
reactjs-id/website-remix pull request #13
Opened 2024-07-08 02:47 UTC by hanihusam

Closes #3

2024-07-08 17:54 UTC, mhaidarhanif requested changes
Need to rebase/merge with the `main` and fix the conflict.

2024-07-08 17:54 UTC, mhaidarhanif commented on app/routes/about.tsx
Focus on what's on the title.

Remove the about page because it's being worked on by @fikrialwan in https://github.com/reactjs-id/website-remix/pull/9

2024-07-09 00:54 UTC, hanihusam commented on app/routes/about.tsx
Sure. Sorry for the mistake.

2024-07-09 02:36 UTC, hanihusam commented
How about the logo, should I init it? @mhaidarhanif

2024-07-09 11:50 UTC, mhaidarhanif commented
@hanihusam The logo just available in the `main` branch.

2024-07-10 17:57 UTC, mhaidarhanif commented
@hanihusam The issue has been resolved by this PR #21

You might need to compare with the existing implementation from `main` and see what can be improved.

2024-07-10 22:50 UTC, hanihusam commented
> @hanihusam The issue has been resolved by this PR #21
> 
> You might need to compare with the existing implementation from `main` and see what can be improved.

Oh, all right.

2024-07-11 07:28 UTC, mhaidarhanif commented
Need to fix conflict again based on the current `main`

2024-07-11 07:28 UTC, mhaidarhanif requested changes
Need to fix conflict again based on the current `main`

2024-07-11 16:53 UTC, mhaidarhanif requested changes
Again need to fix conflict

2024-07-12 18:34 UTC, mhaidarhanif approved these changes
Finally, all good now 👍

2024-07-12 18:34 UTC, merged